server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "App to retrieve users"
appVersion: "1.0.0"
